#!/bin/bash

echo
echo -----------------------
echo "RUNNING NOSTR BOTS >> $(date)"

while true; do
    for env_file in ./active_bots/*.env; do
        echo "..."
        echo "env_file: $(basename $env_file)"

        unset NOSPY_USER
        unset RSS_FEED_URL
        unset BEHAVIOR_SCRIPT
        source $env_file
        echo "NOSPY_USER: $NOSPY_USER"
        echo "RSS_FEED_URL: $RSS_FEED_URL"
        echo "BEHAVIOR_SCRIPT: $BEHAVIOR_SCRIPT"

        if [ "$BEHAVIOR_SCRIPT" == "rss_bot" ]; then
            ./rss_bot
        fi
    done

    echo "..."
    echo "sleeping 360 seconds..."
    sleep 360
done
