#!/bin/bash

figlet -f slant "Enable a Nostr RSS Bot"
echo ----------------------------------------
echo
echo "NOTE: This script SHOULD be run as root."
echo
echo "This script creates an systemd service for an already-created nostr bot script."
echo
read -p "Press Enter to continue or Ctrl+C to cancel."
echo

# SET USERNAME
read -p "nostr-bot username: " username
NOSPY_USER=$username
if [ -z "$NOSPY_USER" ]; then
    echo "username cannot be empty"
    exit 1
fi

read -p "script filename: (leave blank to default to rss@$NOSPY_USER)" script_filename
if [ -z "$script_filename" ]; then
    script_filename=rss@$NOSPY_USER
fi

linuxuser=satoshi
# script_filename=rss@$NOSPY_USER
script_fullpath=/home/$linuxuser/$script_filename
service_filename=rss@$NOSPY_USER.service
service_fullpath=/etc/systemd/system/$service_filename

echo
echo "Creating systemd service for $NOSPY_USER"
echo "$service_fullpath"
echo

# cat << EOF > "/etc/systemd/system/scrape@$NOSPY_USER.service"
cat << EOF > "$service_fullpath"
[Unit]
Description=nostr rss bot service for nospy user $NOSPY_USER
After=network.target

[Service]
User=$linuxuser
WorkingDirectory=/home/$linuxuser
ExecStart=/bin/bash $script_fullpath
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# make systemd aware of new service
systemctl daemon-reload

# start newly created service
echo systemctl start $service_filename

# start automatically when system boots
echo systemctl enable $service_filename

# check status of service
echo systemctl status $service_filename

echo
echo done.
echo